SET IDENTITY_INSERT [dbo].[ArtistAlbums] ON
INSERT INTO [dbo].[ArtistAlbums] ([Id], [ArtistId], [AlbumId]) VALUES (1, 2, 1)
INSERT INTO [dbo].[ArtistAlbums] ([Id], [ArtistId], [AlbumId]) VALUES (2, 2, 1)
INSERT INTO [dbo].[ArtistAlbums] ([Id], [ArtistId], [AlbumId]) VALUES (3, 4, 2)
INSERT INTO [dbo].[ArtistAlbums] ([Id], [ArtistId], [AlbumId]) VALUES (4, 5, 3)
INSERT INTO [dbo].[ArtistAlbums] ([Id], [ArtistId], [AlbumId]) VALUES (5, 6, 4)
INSERT INTO [dbo].[ArtistAlbums] ([Id], [ArtistId], [AlbumId]) VALUES (6, 7, 5)
INSERT INTO [dbo].[ArtistAlbums] ([Id], [ArtistId], [AlbumId]) VALUES (7, 8, 6)
INSERT INTO [dbo].[ArtistAlbums] ([Id], [ArtistId], [AlbumId]) VALUES (8, 9, 7)
INSERT INTO [dbo].[ArtistAlbums] ([Id], [ArtistId], [AlbumId]) VALUES (9, 10, 8)
INSERT INTO [dbo].[ArtistAlbums] ([Id], [ArtistId], [AlbumId]) VALUES (10, 11, 9)
INSERT INTO [dbo].[ArtistAlbums] ([Id], [ArtistId], [AlbumId]) VALUES (11, 12, 10)
INSERT INTO [dbo].[ArtistAlbums] ([Id], [ArtistId], [AlbumId]) VALUES (12, 13, 11)
INSERT INTO [dbo].[ArtistAlbums] ([Id], [ArtistId], [AlbumId]) VALUES (13, 14, 12)
INSERT INTO [dbo].[ArtistAlbums] ([Id], [ArtistId], [AlbumId]) VALUES (14, 15, 13)
INSERT INTO [dbo].[ArtistAlbums] ([Id], [ArtistId], [AlbumId]) VALUES (15, 16, 14)
INSERT INTO [dbo].[ArtistAlbums] ([Id], [ArtistId], [AlbumId]) VALUES (16, 17, 15)
INSERT INTO [dbo].[ArtistAlbums] ([Id], [ArtistId], [AlbumId]) VALUES (17, 18, 16)
INSERT INTO [dbo].[ArtistAlbums] ([Id], [ArtistId], [AlbumId]) VALUES (18, 19, 17)
INSERT INTO [dbo].[ArtistAlbums] ([Id], [ArtistId], [AlbumId]) VALUES (19, 20, 18)
SET IDENTITY_INSERT [dbo].[ArtistAlbums] OFF
